---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo-dev
  chart:
    git: github.com:suresh58/helm-operator-get-started
    path: sv-nginx
    ref: master
  values:
    image: nginx
    replicaCount: 1
    hpa:
      enabled: false